import { CodeBlock } from "@/components/CodeBlock/code-block";
import Link from "next/link";

const SymfonyApiTestingCourse = () => {
    return (
        <div className="px-5 py-8 font-sans">
            <h1 className="text-3xl font-semibold mb-6 text-center">Testing/Consuming an API</h1>
            <p className="text-lg mb-6">
                In this phase, you will learn how to test and consume an API. There are several ways to do this:
            </p>

            <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-2">Testing via Swagger Interface</h2>
                <div className="border-b border-gray-300 mb-6" />

                <p className="text-lg leading-relaxed mb-4">
                    You can test your API directly using the Swagger interface generated by API Platform. Simply navigate to <code>http://127.0.0.1:8000/api</code> in your browser to access the interactive API documentation.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-2">Testing Using Postman or Insomnia</h2>
                <div className="border-b border-gray-300 mb-6" />

                <p className="text-lg leading-relaxed mb-4">
                    Another option is to use Postman or Insomnia, which are popular tools for testing APIs. You can install these tools from the Ubuntu Store.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-2">Testing with VSCode RestClient Extension</h2>
                <div className="border-b border-gray-300 mb-6" />

                <p className="text-lg leading-relaxed mb-4">
                    You can also use the RestClient extension in Visual Studio Code. After installing the extension, create a <code>.http</code> or <code>.rest</code> file and add the following line:
                </p>
                <CodeBlock code={`GET http://api.themoviedb.org/3/search/movie?api_key=f33cd318f5135dba306176c13104506a&query=avenger`} />

                <p className="text-lg leading-relaxed mb-4">
                    Once the request is added, click on <strong>Send Request</strong> to execute it and view the response.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-2">Exercise</h2>
                <div className="border-b border-gray-300 mb-6" />

                <p className="text-lg leading-relaxed mb-4">
                    In this exercise, we will work with the Symfony project <code>monProjet</code> and perform the following tasks:
                </p>
                <ul className="list-disc ml-6 mb-4">
                    <li>Add serialization contexts (Groups) to all properties of the <code>Artist</code> and <code>Disc</code> entities.</li>
                    <li>Expose the <code>Contact</code> entity on your API. This entity will handle the contact form, and its documentation will only be visible to users with the <code>ROLE_ADMIN</code> (you can find help <a className="text-blue-600" href="https://api-platform.com/docs/core/security/">here</a>).</li>
                </ul>
            </section>

            <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-2">Authentication with JWT (Optional)</h2>
                <div className="border-b border-gray-300 mb-6" />

                <p className="text-lg leading-relaxed mb-4">
                    If you are interested in implementing API authentication using the JWT (JSON Web Token) standard, you can refer to the following resource to learn how to set it up.
                </p>

                <div className="text-center mt-8">
                    <Link href="/MVC/API/api03_consumingapi/JWT" className="text-xl font-semibold text-blue-600 underline">
                        Authentication with JWT
                    </Link>
                </div>
            </section>
        </div>
    );
};

export default SymfonyApiTestingCourse;
