'use client';

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, Terminal } from "lucide-react";

export default function GitIgnorePage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-background to-muted">
      <div className="container mx-auto px-4 ">
        {/* Introduction */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>What is .gitignore?</CardTitle>
            <CardDescription>Excluding unwanted files from version control</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-lg leading-relaxed mb-4">
              The `.gitignore` file tells Git which files (or patterns) it should ignore. This helps
              keep unnecessary files, such as temporary files or system files, from being committed to
              the repository.
            </p>
            <div className="grid md:grid-cols-2 gap-4 mt-4">
              <Card className="p-4">
                <h3 className="font-semibold mb-2">Why use .gitignore?</h3>
                <p className="text-sm text-muted-foreground">
                  By ignoring files that are not relevant to the project (e.g., log files, compiled
                  binaries), you ensure that your repository remains clean and manageable.
                </p>
              </Card>
              <Card className="p-4">
                <h3 className="font-semibold mb-2">Common Ignored Files</h3>
                <p className="text-sm text-muted-foreground">
                  Files like system files, IDE configurations, and build artifacts are commonly ignored
                  to avoid polluting the version history.
                </p>
              </Card>
            </div>
          </CardContent>
        </Card>

        {/* Basic .gitignore Example */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Basic .gitignore Structure</CardTitle>
            <CardDescription>Creating and configuring a .gitignore file</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Alert>
              <Terminal className="h-4 w-4" />
              <AlertDescription>
                Example of a simple .gitignore file for common cases
              </AlertDescription>
            </Alert>
            <div className="space-y-4">
              <div className="bg-muted p-4 rounded-lg">
                <code className="text-sm">*.log</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Ignore all log files generated by the system
                </p>
              </div>
              <div className="bg-muted p-4 rounded-lg">
                <code className="text-sm">node_modules/</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Ignore the node_modules folder which contains all your project's dependencies
                </p>
              </div>
              <div className="bg-muted p-4 rounded-lg">
                <code className="text-sm">*.env</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Ignore environment variable files to avoid exposing sensitive data
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Configuration */}
        <Card>
          <CardHeader>
            <CardTitle>Customizing .gitignore</CardTitle>
            <CardDescription>How to fine-tune your .gitignore rules</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Alert>
              <FileText className="h-4 w-4" />
              <AlertDescription>
                Customize your .gitignore file according to your project needs
              </AlertDescription>
            </Alert>
            <div className="bg-muted p-4 rounded-lg space-y-4">
              <div>
                <code className="text-sm"># Ignore compiled Python files</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Add a comment for better understanding and maintenance of your .gitignore rules
                </p>
              </div>
              <div>
                <code className="text-sm">*.pyc</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Ignore Python bytecode files, which are not needed in the repository
                </p>
              </div>
              <div>
                <code className="text-sm">.vscode/</code>
                <p className="text-sm text-muted-foreground mt-2">
                  Ignore Visual Studio Code workspace settings to avoid versioning personal preferences
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
